### ISSUE TITLE
NoSubstitution mark/reason

### ISSUE THREAD

**Issue by rlindstrm** [IHE/pharm-meow#17]
Should it be on TreatmentLine?
It's definitely on prescription, but I'd think it should also be on TreatmentLine.

**Comment by costateixeira** [comment]
If 'no substitution' is a clinical attribute that may relate to anything
beyond the dispensing, then yes. For example when 'do not substitute'
applies to the several prescriptions that are derived from a line.
I think we should indeed have 'no substitution' at the treatment line.

**Comment by rlindstrm** [comment]
No substitution mark and reason added to the treatment line logical model, reason can be coded or textual. 
For the group to review.

**Comment by rlindstrm** [comment]
continued in #40
