### ISSUE TITLE
FHIR resources and their role in this context

### ISSUE THREAD

**Issue by rlindstrm** [IHE/pharm-meow#2]
MedicationStatement
MedicationRequest
MedicationDispense
MedicationAdministration?
Medication
CarePlan (mentioned, but out of scope?)
...

**Comment by rlindstrm** [comment]
[Estonian draft on this](https://docs.google.com/presentation/d/12D6MhNnr1woWotwgEkYlyXm-CU8dZlSIadhrLt4V5II/edit?usp=sharing)
CarePlan we consider to be out of scope. From our side, the clinical workflows are still on CDA, and the CarePlan would at best be an artificial extra that actually is not used in a workflow.

**Comment by rlindstrm** [comment]
Related to #5

**Comment by rlindstrm** [comment]
https://chat.fhir.org/#narrow/stream/179249-Medication/topic/MedicationOverview.20-.20Document.20Bundle.20or.20List

**Comment by costateixeira** [comment]
We will consider but not enforce the use of documents or Lists.
There should be a section in the IG showing when to use one  or the other, and the impact this has.
The "core" of the profile is the ability to express the medication lines in a consistent way across all these types of presentation and their rules (i.e. "above" prescriptions and dispenses).
This would be an option in IHE:

We will use only a PULL mechanism.

Options:
1. Document: The transaction would be "Retrieve document": 
2. List: The transaction would mean "Get me the treatment lines for this patient" : `GET List?type=Medication` or `GET MedicationStatement?_list=List001`
3. Not for foreground IHE transaction: "Raw" get the resources `GET MedicationStatement`
